### PR TITLE
Capitalize folder names.  Capitalize instantiable ts classes

### PR DESCRIPTION
**Pull request by joelhoisko**
running `yarn build` would break on my case sensitive linux system. ~~I've chosen to adapt capitalized names for folders and lowercase for the app.js, home.js etc files even though they are instantiated.~~ Input on  this?

### CODE REVIEW

**Comment by joelhoisko** [comment]
On one hand, it makes more sense to have the js/ts files capitalized according to the convention that:
> things that can be instantiated should be PascalCase, while non instantiatables be camelCase

Making `app.ts` actually `App.ts` etc. Or are there more conventions here at play, like does Aurelia have it's own convention of having all js/ts files lowercase thanks to how Aurelia imports them into html files?

**Comment by woksin** [comment]
NIce. Let's stick to the conventions for JS/TS. Though I'm a but unsure about the capitalization on html scss. Need input from @Virrum . Though IMO i think they should follow the same capitalization

**Comment by joelhoisko** [comment]
I've used these capitalization rules also in https://github.com/dolittle-samples/ToDolittle/pull/2

**Comment by pavsaund** [comment]
Like you mention @joelhoisko, there's some friction between JS/TS naming conventions and aurelia naming conventions. But you also need to take our proxy generation into the mix.

Aurelia prefers kebab-case for their component file names, since this also represents how a component will be referenced in the HTML. When it comes to the class itself, they use standard JS/TS conventions, and adhere to instantiable modules as PascalCase, and non-instantiable modules as camelCased.

So, a NavBar component will be represented like this:
```bash
└─ nav-bar
   ├─ nav-bar.html
   └─ nav-bar.ts
```
```html
  <nav-bar></nav-bar>
```
```ts
  export class NavBar { ... }
```

without being sure, I believe the idea is to take file casing out of the equation, and instead kebab-case everything, including models, classes, types and helpers. 

This approach crashes with the traditional JS/TS convention of PascalCase for classes and camelCase for other modules.  

What is more important to discuss, though is proxy generation, and how this fits into the mix Everything proxy generateion adheres to C# standards, since this is the source. Meaning PascalCase for folders and classes. This will crash magnificently with any lower-case convention in the frotnend.

example: Feature in backend named "Customers", and top-level navigation route in frontend named "customers". All proxies will attempt to generate to Customers/ProxyName.js, and all frotnend components will be lower cased to `index.html`. This will work fine on Windows and OSX, but on any *nix system it will explode with missing files.

I've already heard of a request to be able to configure proxies to generate to kebab-case, and I'm sure others have other preferences, At the end of the day, even if I don't like it, I wonder if our defaults should be PascalCased for folders and otherwise follow JS/TS conventions - only to avoid the problem with proxies?

**Comment by joelhoisko** [comment]
>I wonder if our defaults should be PascalCased for folders and otherwise follow JS/TS conventions - only to avoid the problem with proxies?

I'd want that to be the norm but problems also arise when following JS/TS conventions because aurelia doesn't quite follow them .

Correct me if I'm wrong here (this is from my experience)
Example: You have a aurelia component in a file called `Customer.ts`. Aurelia won't kebab-case a single capitalized word (`-customer` doesn't really make sense) so it will just keep the upper capitalized word and look for `Customer.html` file which is very much against html conventions.

Using Pascal/camelCase for JS/TS files seems to work as long as they don't get sucked into aurelias custom element naming system, so a file like `customer-table.ts` could still easily import files like `CustomerTableProxy.ts`. It's just that aurelia really want's all aurelia component files to be kebab-cased.
I'm kinda starting to think that we should have a standard for all aurelia/UI-element stuff (kebab-case) and then whatever business logic/backend proxies you use should then follow PascalCase/camelCase as it's tied to the backend or is pure JS/TS. Ofc this line gets very muddy with what is just UI and what is logic but that's a thought still.

With folders I agree that PascalCase should be the way as it is for the rest of dolittle projects folders. Or is there an argument to be made against folders being PascalCase? Or does aurelia kebab-case folder names?

```html
<require from="./AmIKebabCasedOrNotAsAFolder/i-am-a-kebab-cased-component"></require>
<!-- or is it like this -->
<require from="./i-am-a-kebab-cased-folder/i-am-a-kebab-cased-component"></require>
```

**Comment by joelhoisko** [comment]
After some testing it seems like that aurelia doesn't kebab-case folder names so this is correct:
```html
<require from="./PascalFolder/kebab-component"></require>
<kebab-component></kebab-component>
```

So using PascalCase for folders seems all fine for me.

I also did more testing regarding the casing of capitalized single word files and my example was correct
>Example: You have a aurelia component in a file called Customer.ts. Aurelia won't kebab-case a single capitalized word (-customer doesn't really make sense) so it will just keep the upper capitalized word and look for Customer.html file which is very much against html conventions.

To add even more spice to the mix it seems like our tests with `mocha` use snake case for folder names etc. But I'm ok with tests having their own conventions regarding filenames/conventions as they don't get picked up by aurelia.

**Pull request merged**
